---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04
#  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
      - recipe[webserver::node_app]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
